# Generated by Django 5.0.6 on 2024-10-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cf_app', '0003_alter_rating_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_app.user')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cf_app.item')),
            ],
        ),
    ]
